MainApp/urls.py
from django.urls import path

from . import views

app_name = 'MainApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'), # an entry is under a topic # variable to associate this entry to this topic
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include # for the home page, include all the urls from the pahe MainApp.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('users/', include('users.urls')), 
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')), # includes all built in urls
    path('register/', views.register, name='register'), # registration page
]

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here # table objects

class Topic(models.Model):  #inheriting all the properties of the models class
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self): #returns back whatever you want it to return, instead of gibberish
        return self.text

# add a new model

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) # allows us to link these two # entry is a foreign key to topic
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return f'{self.text[:50]}...'
    

users/models.py
from django.db import models

# Create your models here.

MainApp/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta: # use the meta class because we already have a model defined called forms
        # bring in all the fields from the model Topic # we only need the text field, which is the name of the attribute
        # to create a new field for the forms that's not linked to the model, you do it before defining the metaclass
        # automatically links the model to the template
        model = Topic
        fields = ['text']
        labels = {'text':''}


class EntryForm(forms.ModelForm):
    class Meta: 
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})} 
        # modifying the look of this box # changing it to be 80 columns so it looks like a big box on the webpage

MainApp/views.py
from django.shortcuts import render, redirect
from .forms import EntryForm, TopicForm
from .models import Entry, Topic
from django.contrib.auth.decorators import login_required
from django.http import Http404 # raise an error if trying to access topic/1 if no topics for the user
# Create your views here. # Home Page

def index(request):
    return render(request, "MainApp/index.html") # rendering a page on your browser, using this template

@login_required
def topics(request):
    #topics = Topic.objects.order_by('-date_added') # add '-' before date for descending order
    # showing all topics, but we only want to load the objects that belong to the user, so we add a filter to the object
    # it has to match the id of the owner # find out who is making the request by saying request.user
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    context = {'topics':topics} # dictionary # 'topics' is the key, is what you have to refer to in the html page 
    return render(request, 'MainApp/topics.html', context)

@login_required
def topic(request, topic_id): 
    topic = Topic.objects.get(id=topic_id) # Topic is a model
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.all() 
    context = {'topic': topic, 'entries': entries} 
    # interview question: dictionary, passes information from the view to use in the template
    # multiple objects that we need to pass # the value is what we are using in the view
    return render(request, 'MainApp/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST': 
        form = TopicForm() # load an empty form because not post request # pass the isntance to the webpage
    else: # it is a post request, we want to pass it on to the database
        form = TopicForm(data=request.POST) # I want to get the data from the post request into this variable called form
        if form.is_valid(): # if you define something as required in the model, and someone doesn't enter the info, the form won't submit
            new_topic = form.save(commit=False) # creates object but hasn't saved it to db
            new_topic.owner = request.user
            new_topic.save()
            return redirect('MainApp:topics') # redirect them to the topics page
    context = {'form':form}
    return render(request, 'MainApp/new_topic.html', context)

@login_required
def new_entry(request, topic_id): # topic_id to identify what topic it is # topic_id is just an integer
    topic = Topic.objects.get(id=topic_id) # topic object

    if topic.owner != request.user:
        raise Http404
        
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False) # the only field that will show up on the webpage is text
            # the entry model has 3 fields: topic, text, date_added(automatic)
            # before we save it, that field is a required field
            # we are not saving it to the database # ready to save but not write yet to the database
            new_entry.topic = topic # from line 34
            new_entry.save()
            return redirect('MainApp:topic', topic_id=topic_id) # what page do we want to load after: the topic page with all the entries showing
            # to load the topic page, you need the topic_id
            # orange in the urls.py file, white in line 34 # what you pass is not an object, it's just an id
    context = {'form':form, 'topic':topic} # we pass topic and form
    return render(request, 'MainApp/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id) # calling the entry object/model
    topic = entry.topic # calling the entry of that topic # topic is an attribute 
    # lower case entry because this is the avriable that is storing that particular object
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry) # we want to grab that particular instance # will load existing data for that entry
    else:
        form = EntryForm(instance=entry, data=request.POST) # take the data on the webpage and put that in the database
        if form.is_valid():
            form.save()
            return redirect('MainApp:topic', topic_id=topic.id) # redirect to that topic page 
    context = {'form':form, 'topic':topic, 'entry': entry} # we pass topic, form and entry # dictionary is growing, passing multiple objects at the same time
    return render(request, 'MainApp/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    # register a new user
    if request.method != 'POST':
        form = UserCreationForm() # display blank registration form
    else:
        form = UserCreationForm(data=request.POST) # process completed form
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('MainApp:index')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)

MainApp/templates/mainapp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Learning Log</a>
    <a href="{% url 'MainApp:topics' %}">Topics</a>

    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}
{% endblock content %}

MainApp/templates/mainapp/edit_entry.html
{% extends "MainApp/base.html"%}

{% block content %}

<p>
    <a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a>
</p>
<!-- link to go back to the topic page
    -->

<p>Edit entry:</p>

<form action="{% url 'MainApp:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save Changes</button>


</form>

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html"%}

{% block content %}

<p>Learning Log helps you keep track of your learning,
    for any topic you're learning about.
</p>

{% endblock content %}

MainApp/templates/mainapp/new_entry.html
{% extends "MainApp/base.html"%}

{% block content %}

<p>
    <a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a>
</p>
<!-- link to go back to the topic page
    -->

<p>Add a new entry:</p>

<form action="{% url 'MainApp:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>


</form>

{% endblock content %}

MainApp/templates/mainapp/new_topic.html
{% extends "MainApp/base.html"%}

{% block content %}

<p>Add a new topic:</p>

<form action="{% url 'MainApp:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>


</form>

{% endblock content %}

MainApp/templates/mainapp/topic.html
{% extends "MainApp/base.html"%}

{% block content %}

<!--

    e.text to call the text attribute
-->

<p>Topic: {{ topic }}</p>
<ul>
    <li>
        {% for e in entries %}
        <p>{{ e.text }}</p>
        <p>{{ e.date_added }}</p>
        <p><a href="{% url 'MainApp:edit_entry' e.id %}">Edit entry</a></p>
    </li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>

<p><a href="{% url 'MainApp:new_entry' topic.id %}">Add new entry</a></p>

<!--
    link
-->

{% endblock content %}

MainApp/templates/mainapp/topics.html
<p>Learning Log</p>


{% extends "MainApp/base.html"%}

{% block content %}

<ul>
    {% for t in topics %}

    <li>
        <a href="{% url 'MainApp:topic' t.id %}">{{ t }}</a>
    </li>

    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'MainApp:new_topic' %}">Add a new topic</a>

{% endblock content %}

users/templates/login.html
{% extends "MainApp/base.html"%}

{% block content %}

{% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Log in</button>
    <input type="hidden" name="text" value="{% url 'MainApp:index' %}" />
</form>

{% endblock content %}